### ISSUE TITLE
tutorial: how to use deepstream with angular2

### ISSUE THREAD

**Issue by gmchaturvedi1** [deepstreamIO/deepstream.io-website-old#24]
dear all,

i am new to deepstream .can u suggest how to connect to deepstream from angular 2 application as i am working in angular2 app .

**Comment by yasserf** [comment]
Deliverable:
1) An angular2 app under : https://github.com/hoxton-one/ds-demo-simple-app-angular2
2) A tutorial on how to use it 

Thanks for raising this @gmchaturvedi1. I'm quite keen to see how angular 2.0 works so might get this done quite soon, but a bit preoccupied with #25 now. 

I'll let you know when we start working on it, but until then, if anyone wants to create the identical feature set as (angular1)[https://github.com/hoxton-one/ds-demo-simple-app-ng] for angular2 please let us know so we don't step on each others toes!

**Comment by gmchaturvedi1** [comment]
Link is not working .

**Comment by yasserf** [comment]
Yep, it's the location we would expect to the angular2 example app to be once it's been created. I removed the http://github from the link to make it unclickable. Sorry for the confusion!
